[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; 921600 在部分 CP2102 板子上燒錄會斷線或 MD5 驗證失敗
upload_speed = 115200
build_flags = -I ${PROJECT_DIR}/../shared
